### PR TITLE
Feat: Added wishlist page.

### PR DESCRIPTION
**Pull request by zoef-yt**
Added wishlist page.

- Made whole wishlist page to show wish-listed items.
- Added small transition on the remove wishlist button
### DEMO

https://user-images.githubusercontent.com/67889207/153722693-bd52b98e-01d0-440c-9268-e798b703a1f3.mp4

### CODE REVIEW

**Comment by Muzammil-khan710** [comment]
Looking great zoef !. Good to merge !

**Review by varun13169 — APPROVED** [review]
Nicely written clean code.

**Review by DivyanshSareen — APPROVED** [review]
Good to merge 👍

**Review by sudipkundu999 — APPROVED** [review]
Loved the animations on hover!
Good to merge!

**Review by zoyatanweer — APPROVED** [review]
nice and clean code. good to merge.

**Review by j24m — APPROVED** [review]
Looks good to merge 👌👌👌

**Pull request merged**
