### PR TITLE
Feat: Add Fav icon to card on hover.

### PR DESCRIPTION
**Pull request by zoef-yt**
Added Favourite icon to the card on hover.
Video demo:

> https://user-images.githubusercontent.com/67889207/153700946-32ce7f16-0de9-490e-b0b6-62dd7df10d34.mp4

### CODE REVIEW

**Review by developer-anand — APPROVED** [review]
Great work Man.

**Review by dev-prabhat — CHANGES_REQUESTED** [review]
image

I think that numeric value should on top-right on that icon

**Comment by zoef-yt** [comment]
> image
> 
> I think that numeric value should on top-right on that icon

will be making that change in my component library.

**Review by dev-prabhat — APPROVED** [review]
Good to go

**Pull request merged**
