### PR TITLE
Feat: added home page to my E-com site.

### PR DESCRIPTION
**Pull request by zoef-yt**
Added home page to my E-commerce site

### CODE REVIEW

**Review by j24m — APPROVED** [review]
Loved it, LGTM <3

**Review by DivyanshSareen — APPROVED** [review]
Looks real good. Epic slider and animations 💯

**Review by zoyatanweer — APPROVED** [review]
clean code, good to merge.

**Review by Shubhamkr2610 — APPROVED** [review]
looks good to me. you are good to go

**Review by purohitdheeraj — APPROVED** [review]
Crazy Stuff!
Awesome Work on Home Page 👍

**Review by archit7448 — APPROVED** [review]
amazing work good to merge

**Pull request merged**
