### PR TITLE
Changed images

### PR DESCRIPTION
**Pull request by zoef-yt**
Changes images to stay consistent.

### CODE REVIEW

**Review by zoyatanweer — APPROVED** [review]
good to mrerge

**Review by sach10-create — APPROVED** [review]
Good to merge

**Review by dev-prabhat — APPROVED** [review]
Good to go

**Review by bhushannaikaroskar — APPROVED** [review]
All good

**Review by sanjitsarkar — APPROVED** [review]
Looks okay

**Pull request merged**
